/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangTransparentaRouteImport } from './routes/$lang/transparenta'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangEventsIndexRouteImport } from './routes/$lang/events/index'
import { Route as LangPagesSlugRouteImport } from './routes/$lang/pages/$slug'
import { Route as LangEventsSlugRouteImport } from './routes/$lang/events/$slug'
import { Route as LangAboutIstoricRouteImport } from './routes/$lang/about.istoric'
import { Route as LangAboutEchipaRouteImport } from './routes/$lang/about.echipa'
import { Route as LangPagesAboutMisiuneaRouteImport } from './routes/$lang/pages/about/misiunea'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangTransparentaRoute = LangTransparentaRouteImport.update({
  id: '/transparenta',
  path: '/transparenta',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangEventsIndexRoute = LangEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LangRoute,
} as any)
const LangPagesSlugRoute = LangPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangEventsSlugRoute = LangEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutIstoricRoute = LangAboutIstoricRouteImport.update({
  id: '/istoric',
  path: '/istoric',
  getParentRoute: () => LangAboutRoute,
} as any)
const LangAboutEchipaRoute = LangAboutEchipaRouteImport.update({
  id: '/echipa',
  path: '/echipa',
  getParentRoute: () => LangAboutRoute,
} as any)
const LangPagesAboutMisiuneaRoute = LangPagesAboutMisiuneaRouteImport.update({
  id: '/pages/about/misiunea',
  path: '/pages/about/misiunea',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRouteWithChildren
  '/$lang/transparenta': typeof LangTransparentaRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/about/echipa': typeof LangAboutEchipaRoute
  '/$lang/about/istoric': typeof LangAboutIstoricRoute
  '/$lang/events/$slug': typeof LangEventsSlugRoute
  '/$lang/pages/$slug': typeof LangPagesSlugRoute
  '/$lang/events/': typeof LangEventsIndexRoute
  '/$lang/pages/about/misiunea': typeof LangPagesAboutMisiuneaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRouteWithChildren
  '/$lang/transparenta': typeof LangTransparentaRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/about/echipa': typeof LangAboutEchipaRoute
  '/$lang/about/istoric': typeof LangAboutIstoricRoute
  '/$lang/events/$slug': typeof LangEventsSlugRoute
  '/$lang/pages/$slug': typeof LangPagesSlugRoute
  '/$lang/events': typeof LangEventsIndexRoute
  '/$lang/pages/about/misiunea': typeof LangPagesAboutMisiuneaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRouteWithChildren
  '/$lang/transparenta': typeof LangTransparentaRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/about/echipa': typeof LangAboutEchipaRoute
  '/$lang/about/istoric': typeof LangAboutIstoricRoute
  '/$lang/events/$slug': typeof LangEventsSlugRoute
  '/$lang/pages/$slug': typeof LangPagesSlugRoute
  '/$lang/events/': typeof LangEventsIndexRoute
  '/$lang/pages/about/misiunea': typeof LangPagesAboutMisiuneaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/transparenta'
    | '/$lang/'
    | '/$lang/about/echipa'
    | '/$lang/about/istoric'
    | '/$lang/events/$slug'
    | '/$lang/pages/$slug'
    | '/$lang/events/'
    | '/$lang/pages/about/misiunea'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/transparenta'
    | '/$lang'
    | '/$lang/about/echipa'
    | '/$lang/about/istoric'
    | '/$lang/events/$slug'
    | '/$lang/pages/$slug'
    | '/$lang/events'
    | '/$lang/pages/about/misiunea'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/transparenta'
    | '/$lang/'
    | '/$lang/about/echipa'
    | '/$lang/about/istoric'
    | '/$lang/events/$slug'
    | '/$lang/pages/$slug'
    | '/$lang/events/'
    | '/$lang/pages/about/misiunea'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transparenta': {
      id: '/$lang/transparenta'
      path: '/transparenta'
      fullPath: '/$lang/transparenta'
      preLoaderRoute: typeof LangTransparentaRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/events/': {
      id: '/$lang/events/'
      path: '/events'
      fullPath: '/$lang/events/'
      preLoaderRoute: typeof LangEventsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/pages/$slug': {
      id: '/$lang/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/$lang/pages/$slug'
      preLoaderRoute: typeof LangPagesSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/events/$slug': {
      id: '/$lang/events/$slug'
      path: '/events/$slug'
      fullPath: '/$lang/events/$slug'
      preLoaderRoute: typeof LangEventsSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about/istoric': {
      id: '/$lang/about/istoric'
      path: '/istoric'
      fullPath: '/$lang/about/istoric'
      preLoaderRoute: typeof LangAboutIstoricRouteImport
      parentRoute: typeof LangAboutRoute
    }
    '/$lang/about/echipa': {
      id: '/$lang/about/echipa'
      path: '/echipa'
      fullPath: '/$lang/about/echipa'
      preLoaderRoute: typeof LangAboutEchipaRouteImport
      parentRoute: typeof LangAboutRoute
    }
    '/$lang/pages/about/misiunea': {
      id: '/$lang/pages/about/misiunea'
      path: '/pages/about/misiunea'
      fullPath: '/$lang/pages/about/misiunea'
      preLoaderRoute: typeof LangPagesAboutMisiuneaRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangAboutRouteChildren {
  LangAboutEchipaRoute: typeof LangAboutEchipaRoute
  LangAboutIstoricRoute: typeof LangAboutIstoricRoute
}

const LangAboutRouteChildren: LangAboutRouteChildren = {
  LangAboutEchipaRoute: LangAboutEchipaRoute,
  LangAboutIstoricRoute: LangAboutIstoricRoute,
}

const LangAboutRouteWithChildren = LangAboutRoute._addFileChildren(
  LangAboutRouteChildren,
)

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRouteWithChildren
  LangTransparentaRoute: typeof LangTransparentaRoute
  LangIndexRoute: typeof LangIndexRoute
  LangEventsSlugRoute: typeof LangEventsSlugRoute
  LangPagesSlugRoute: typeof LangPagesSlugRoute
  LangEventsIndexRoute: typeof LangEventsIndexRoute
  LangPagesAboutMisiuneaRoute: typeof LangPagesAboutMisiuneaRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRouteWithChildren,
  LangTransparentaRoute: LangTransparentaRoute,
  LangIndexRoute: LangIndexRoute,
  LangEventsSlugRoute: LangEventsSlugRoute,
  LangPagesSlugRoute: LangPagesSlugRoute,
  LangEventsIndexRoute: LangEventsIndexRoute,
  LangPagesAboutMisiuneaRoute: LangPagesAboutMisiuneaRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
