/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparentaRouteImport } from './routes/transparenta'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as AboutIstoricRouteImport } from './routes/about.istoric'
import { Route as AboutEchipaRouteImport } from './routes/about.echipa'
import { Route as PagesAboutMisiuneaRouteImport } from './routes/pages/about/misiunea'

const TransparentaRoute = TransparentaRouteImport.update({
  id: '/transparenta',
  path: '/transparenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIstoricRoute = AboutIstoricRouteImport.update({
  id: '/istoric',
  path: '/istoric',
  getParentRoute: () => AboutRoute,
} as any)
const AboutEchipaRoute = AboutEchipaRouteImport.update({
  id: '/echipa',
  path: '/echipa',
  getParentRoute: () => AboutRoute,
} as any)
const PagesAboutMisiuneaRoute = PagesAboutMisiuneaRouteImport.update({
  id: '/pages/about/misiunea',
  path: '/pages/about/misiunea',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/transparenta': typeof TransparentaRoute
  '/about/echipa': typeof AboutEchipaRoute
  '/about/istoric': typeof AboutIstoricRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/about/misiunea': typeof PagesAboutMisiuneaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/transparenta': typeof TransparentaRoute
  '/about/echipa': typeof AboutEchipaRoute
  '/about/istoric': typeof AboutIstoricRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/about/misiunea': typeof PagesAboutMisiuneaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/transparenta': typeof TransparentaRoute
  '/about/echipa': typeof AboutEchipaRoute
  '/about/istoric': typeof AboutIstoricRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/about/misiunea': typeof PagesAboutMisiuneaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/transparenta'
    | '/about/echipa'
    | '/about/istoric'
    | '/pages/$slug'
    | '/pages/about/misiunea'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/transparenta'
    | '/about/echipa'
    | '/about/istoric'
    | '/pages/$slug'
    | '/pages/about/misiunea'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/transparenta'
    | '/about/echipa'
    | '/about/istoric'
    | '/pages/$slug'
    | '/pages/about/misiunea'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  TransparentaRoute: typeof TransparentaRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PagesAboutMisiuneaRoute: typeof PagesAboutMisiuneaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparenta': {
      id: '/transparenta'
      path: '/transparenta'
      fullPath: '/transparenta'
      preLoaderRoute: typeof TransparentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/istoric': {
      id: '/about/istoric'
      path: '/istoric'
      fullPath: '/about/istoric'
      preLoaderRoute: typeof AboutIstoricRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/echipa': {
      id: '/about/echipa'
      path: '/echipa'
      fullPath: '/about/echipa'
      preLoaderRoute: typeof AboutEchipaRouteImport
      parentRoute: typeof AboutRoute
    }
    '/pages/about/misiunea': {
      id: '/pages/about/misiunea'
      path: '/pages/about/misiunea'
      fullPath: '/pages/about/misiunea'
      preLoaderRoute: typeof PagesAboutMisiuneaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutEchipaRoute: typeof AboutEchipaRoute
  AboutIstoricRoute: typeof AboutIstoricRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutEchipaRoute: AboutEchipaRoute,
  AboutIstoricRoute: AboutIstoricRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  TransparentaRoute: TransparentaRoute,
  PagesSlugRoute: PagesSlugRoute,
  PagesAboutMisiuneaRoute: PagesAboutMisiuneaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
